# Set variables once
variables:
  buildResultPath: 'C:\agent_build'
  deployResultPath: 'C:\temp'

pool:
  name: Default

stages:
- stage: Build123
  jobs:
  - job: BuildingTest
    steps:
    # Build with Apache Ant
    - task: Ant@1
      inputs:
        buildFile: 'build.xml'
    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(buildResultPath)'
        #pathtoPublish: '$(buildResultPath)'
        artifactName: drop        


          
            


