# Set variables once
variables:
  buildResultPath: 'C:\agent_build'

pool:
  name: Default

steps:
# Build with Apache Ant
- task: Ant@1
  inputs:
    buildFile: 'build.xml'



- task: CopyFiles@2
  inputs:
    contents: '*.txt'
    targetFolder: $(buildResultPath)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(buildResultPath)
    artifactName: MyBuildOutputs
