# Set variables once
variables:
  buildResultPath: 'C:\agent_build'
  deployResultPath: 'C:\temp'

pool:
  name: Default

stages:
- stage: Build123
  jobs:
  - job: BuildingTest
    steps:



    - task: BatchScript@1
      inputs:
        filename: 'C:\alm\ant\bin\ant.bat'
        #arguments: 'justtesting'
        workingFolder: 'C:\agent_build'
        failOnStandardError: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: 'C:\agent_build' 
        artifactName: 'drop' 
        publishLocation: 'filePath'
        targetPath: 'C:\agent_build\test'
        fileCopyOptions: '*.txt'

            

- stage: deploy
  dependsOn: Build123
  condition: succeeded('Build123')
  jobs:
  - deployment: DeployTest
    displayName: deploy testing
    # creates an environment if it doesn't exist
    environment: 'IkanDeploy'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'This is the end of the deploy stage'             
          - script: echo '$(System.DefaultWorkingDirectory)'
          - script: echo '$(Build.BinariesDirectory)'
          - download: current
            artifact: drop

