pool:
  name: Default

steps:
# Build with Apache Ant
- task: Ant@1
  inputs:
    buildFile: 'build.xml'



- task: CopyFiles@2
  inputs:
    contents: '_buildOutput/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
