# Set variables once
variables:
  buildResultPath: 'C:\agent_build'

pool:
  name: Default

stages:
- stage: Build123
  jobs:
  - job: BuildingTest
    steps:
    # Build with Apache Ant
    - task: Ant@1
      inputs:
        buildFile: 'build.xml'

- stage: Test123
  dependsOn: Build123
  condition: succeeded('Build123')
  jobs:
  - job: TestTest
    steps:
    - script: echo 'inside B123 now'



