# Set variables once
variables:
  buildResultPath: 'C:\agent_build'
  deployResultPath: 'C:\temp'

pool:
  name: Default

stages:
- stage: Build123
  jobs:
  - job: BuildingTest
    steps:
    # Build with Apache Ant
    - task: Ant@1
      inputs:
        buildFile: 'build.xml'
    - task: PublishBuildArtifacts@1
      inputs:
        #pathtoPublish: '$(System.DefaultWorkingDirectory)'
        pathtoPublish: '$(buildResultPath)'
        artifactName: drop        


- stage: deploy
  dependsOn: Build123
  condition: succeeded('Build123')
  jobs:
  - deployment: DeployTest
    displayName: deploy testing
    # creates an environment if it doesn't exist
    environment: 'IkanDeploy'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: WebSite
              downloadPath: $(buildResultPath)
            
          - task: CopyFiles@2
            displayName: 'Copy Files'
            inputs:
              SourceFolder: '$(buildResultPath)'
              #Contents: '**/*.?(txt)'
              Contents: '*.txt'
              TargetFolder: $(deployResultPath)
              #TargetFolder: 'C:\temp'            
            


