# Set variables once
variables:
  buildResultPath: 'C:\agent_build'

pool:
  name: Default

stages:
- stage: Build123
  jobs:
  - job: BuildingTest
    steps:
    # Build with Apache Ant
    - task: Ant@1
      inputs:
        buildFile: 'build.xml'




    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        #Contents: '**/*.?(txt)'
        Contents: '*.txt'
        TargetFolder: $(Build.ArtifactStagingDirectory)
        #TargetFolder: 'C:\temp'

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop


- stage: deploy
  dependsOn: Build123
  condition: succeeded('Build123')
  jobs:
  - deployment: DeployTest
    displayName: deploy testing
    # creates an environment if it doesn't exist
    environment: 'IkanDeploy'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo 'This is the end of the deploy stage'         
          - script: echo '$(System.DefaultWorkingDirectory)'
          - download: current
            artifact: drop
            


