# Set variables once
variables:
  buildResultPath: 'C:\agent_build'
  deployResultPath: 'C:\temp'

pool:
  name: Default

stages:
- stage: Build123
  jobs:
  - job: BuildingTest
    steps:



    - task: BatchScript@1
      inputs:
        filename: 'C:\alm\ant\bin\ant.bat'
        #arguments: 'justtesting.xml'
        workingFolder: 'C:\agent_build'
        failOnStandardError: true
          
            


